In [ ]:
# Installing Pandas
pip install pandas

In [ ]:
# Installing Matplot Lib
pip install matplotlib

In [ ]:
# Installing Seaborn
pip install seaborn

In [ ]:
# Installing Scipy
pip install scipy

In [3]:
# Importing essential Libbraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats  import zscore

In [4]:
# Imprting the filing & loading it to a pandas Data Frame
path = r"C:\Users\henokt\OneDrive - Inchcape\Documents\KIAM8\Data\data\data\benin-malanville.csv"
df=pd.read_csv(path.replace('\\','/'))

In [4]:
# Exploring the Data Set
df.describe()

,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB,Comments
count,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,0.0
mean,240.559452,167.187516,115.358961,236.589496,228.883576,28.179683,54.487969,2.121113,2.809195,0.473390,153.435172,8.582407,994.197199,0.000923,0.001905,35.246026,32.471736,NaN
std,331.131327,261.710501,158.691074,326.894859,316.536515,5.924297,28.073069,1.603466,2.029120,0.273395,102.332842,6.385864,2.474993,0.030363,0.037115,14.807258,12.348743,NaN
min,-12.900000,-7.800000,-12.600000,0.000000,0.000000,11.000000,2.100000,0.000000,0.000000,0.000000,0.000000,0.000000,985.000000,0.000000,0.000000,9.000000,8.100000,NaN
25%,-2.000000,-0.500000,-2.100000,0.000000,0.000000,24.200000,28.800000,1.000000,1.300000,0.400000,59.000000,3.700000,993.000000,0.000000,0.000000,24.200000,23.600000,NaN
50%,1.800000,-0.100000,1.600000,4.500000,4.300000,28.000000,55.100000,1.900000,2.600000,0.500000,181.000000,8.600000,994.000000,0.000000,0.000000,30.000000,28.900000,NaN
75%,483.400000,314.200000,216.300000,463.700000,447.900000,32.300000,80.100000,3.100000,4.100000,0.600000,235.100000,12.300000,996.000000,0.000000,0.000000,46.900000,41.500000,NaN
max,1413.000000,952.300000,759.200000,1342.300000,1342.300000,43.800000,100.000000,19.500000,26.600000,4.200000,360.000000,99.400000,1003.000000,1.000000,2.500000,81.000000,72.500000,NaN

In [ ]:
# Checking for Missing Values-1
df.isna().any()

Timestamp        False
GHI              False
DNI              False
DHI              False
ModA             False
ModB             False
Tamb             False
RH               False
WS               False
WSgust           False
WSstdev          False
WD               False
WDstdev          False
BP               False
Cleaning         False
Precipitation    False
TModA            False
TModB            False
Comments          True
dtype: bool

In [ ]:
# Checking for Missing Values-2
df.isna().sum()

Timestamp             0
GHI                   0
DNI                   0
DHI                   0
ModA                  0
ModB                  0
Tamb                  0
RH                    0
WS                    0
WSgust                0
WSstdev               0
WD                    0
WDstdev               0
BP                    0
Cleaning              0
Precipitation         0
TModA                 0
TModB                 0
Comments         525600
dtype: int64

In [ ]:
# Checking for Outliers DNI

Q1_GHI = df['GHI'].quantile(0.25)
Q3_GHI = df['GHI'].quantile(0.75)

IQR_GHI = Q3_GHI -Q1_GHI

Lower_Bound_GHI = Q1_GHI - 1.5 * IQR_GHI
Upper_Bound_GHI = Q3_GHI + 1.5 * IQR_GHI

GHI_Outliers = df[(df['GHI']<Lower_Bound_GHI) | (df['GHI']> Upper_Bound_GHI) ]

GHI_Outliers

,Timestamp,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB,Comments
671,2021-08-09 11:12,1274.0,698.8,615.2,1210.3,1210.3,30.1,69.6,3.4,4.1,0.6,175.8,13.3,999,0,0.0,63.7,53.1,NaN
674,2021-08-09 11:15,1349.0,771.8,618.0,1281.5,1281.5,30.9,67.1,4.0,4.6,0.4,169.1,12.3,999,0,0.0,65.0,53.5,NaN
676,2021-08-09 11:17,1334.0,751.9,620.0,1267.3,1267.3,31.1,67.0,2.7,3.6,0.6,208.0,15.9,999,0,0.0,66.0,53.9,NaN
849,2021-08-09 14:10,1253.0,714.8,552.5,1156.0,1155.0,31.0,64.2,3.3,3.9,0.5,241.2,7.9,997,0,0.0,57.6,52.1,NaN
850,2021-08-09 14:11,1324.0,813.0,532.3,1218.0,1217.0,31.0,62.9,2.2,3.1,0.6,225.6,10.7,997,0,0.0,58.7,53.6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522046,2022-08-06 12:47,1218.0,619.7,580.5,1130.0,1128.0,30.3,70.7,3.5,4.4,0.6,266.2,13.5,996,0,0.0,55.1,48.2,NaN
522067,2022-08-06 13:08,1218.0,724.9,477.8,1137.0,1133.0,30.5,67.3,4.3,5.6,1.1,258.9,10.3,996,0,0.0,53.9,47.5,NaN
522073,2022-08-06 13:14,1218.0,759.1,446.2,1120.0,1112.0,30.9,66.3,4.3,5.1,0.6,297.6,9.8,996,0,0.0,61.6,53.1,NaN
522074,2022-08-06 13:15,1262.0,772.4,475.8,1166.0,1153.0,31.1,66.0,3.4,4.6,0.7,288.7,14.6,996,0,0.0,62.1,53.1,NaN
522075,2022-08-06 13:16,1289.0,758.1,519.2,1191.0,1179.0,31.4,65.9,4.1,5.1,0.7,259.4,13.9,996,0,0.0,63.0,54.0,NaN

In [ ]:
# Checking for Outliers DHI

Q1_DHI = df['DHI'].quantile(0.25)
Q3_DHI = df['DHI'].quantile(0.75)

IQR_DHI = Q3_DHI -Q1_DHI

Lower_Bound_DHI = Q1_DHI - 1.5 * IQR_DHI
Upper_Bound_DHI = Q3_DHI + 1.5 * IQR_DHI

DHI_Outliers = df[(df['DHI']<Lower_Bound_DHI) | (df['DHI']> Upper_Bound_DHI) ]

DHI_Outliers

,Timestamp,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB,Comments
850,2021-08-09 14:11,1324.0,813.0,532.3,1218.0,1217.0,31.0,62.9,2.2,3.1,0.6,225.6,10.7,997,0,0.0,58.7,53.6,NaN
868,2021-08-09 14:29,1216.0,791.9,468.3,1118.0,1118.0,31.1,64.5,3.4,4.6,0.8,275.0,10.6,997,0,0.0,58.0,56.3,NaN
869,2021-08-09 14:30,1196.0,791.8,450.9,1098.0,1096.0,31.3,64.6,2.6,3.9,0.7,256.1,11.9,997,0,0.0,58.3,56.3,NaN
870,2021-08-09 14:31,1201.0,802.0,449.7,1102.0,1100.0,31.5,63.9,3.4,4.4,0.7,246.0,13.6,997,0,0.0,58.6,56.7,NaN
871,2021-08-09 14:32,1197.0,792.5,456.0,1098.0,1097.0,31.6,65.0,3.2,4.1,0.6,243.3,12.5,997,0,0.0,59.1,57.2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523540,2022-08-07 13:41,1051.0,796.4,256.6,956.0,948.0,33.1,59.3,2.5,3.1,0.5,284.4,13.7,994,0,0.0,60.4,54.2,NaN
523541,2022-08-07 13:42,1062.0,798.6,265.2,964.0,957.0,33.2,58.7,2.8,3.9,0.6,282.8,14.9,994,0,0.0,60.8,54.7,NaN
523542,2022-08-07 13:43,1072.0,797.0,275.9,973.0,966.0,33.3,59.6,3.2,4.6,0.8,284.0,15.3,994,0,0.0,61.1,54.9,NaN
523543,2022-08-07 13:44,1091.0,794.6,296.2,993.0,987.0,33.2,58.3,3.0,4.4,0.8,277.1,22.7,994,0,0.0,60.8,54.6,NaN
523553,2022-08-07 13:54,1091.0,786.3,314.4,995.0,989.0,32.7,62.1,2.9,4.6,0.9,272.1,11.2,994,0,0.0,53.4,49.2,NaN

In [12]:
# Checking for Outliers DHI

Q1_DHI = df['DHI'].quantile(0.25)
Q3_DHI = df['DHI'].quantile(0.75)

IQR_DHI = Q3_DHI -Q1_DHI

Lower_Bound_DHI = Q1_DHI - 1.5 * IQR_DHI
Upper_Bound_DHI = Q3_DHI + 1.5 * IQR_DHI

DHI_Outliers = df[(df['DHI']<Lower_Bound_DHI) | (df['DHI']> Upper_Bound_DHI) ]

DHI_Outliers

,Timestamp,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB,Comments
668,2021-08-09 11:09,843.0,304.1,554.9,790.5,796.6,30.2,69.1,2.3,3.6,0.8,171.3,25.8,999,0,0.0,62.2,52.1,NaN
669,2021-08-09 11:10,776.4,201.1,583.3,740.4,745.0,30.2,69.0,2.8,3.6,0.6,171.8,20.1,999,0,0.0,62.6,52.6,NaN
670,2021-08-09 11:11,836.0,235.0,610.6,778.8,783.8,30.3,68.2,3.2,4.1,0.7,190.5,18.4,999,0,0.0,63.0,52.7,NaN
671,2021-08-09 11:12,1274.0,698.8,615.2,1210.3,1210.3,30.1,69.6,3.4,4.1,0.6,175.8,13.3,999,0,0.0,63.7,53.1,NaN
672,2021-08-09 11:13,938.0,340.1,612.8,891.1,891.1,30.4,68.4,3.4,4.6,0.9,171.5,11.9,999,0,0.0,65.8,54.3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524921,2022-08-08 12:42,723.9,161.8,554.7,678.7,676.7,30.7,70.9,5.2,7.2,0.7,214.1,9.9,995,0,0.0,57.7,49.2,NaN
524937,2022-08-08 12:58,687.3,134.5,546.3,644.8,642.2,30.3,72.7,4.3,5.4,0.8,230.1,14.0,994,0,0.0,51.7,45.3,NaN
524938,2022-08-08 12:59,680.5,129.4,544.3,643.6,640.7,30.3,73.4,4.4,5.1,0.5,237.2,9.1,994,0,0.0,52.0,45.3,NaN
524964,2022-08-08 13:25,683.3,131.4,545.4,644.2,636.0,30.8,69.7,4.6,5.4,0.7,230.0,7.1,994,0,0.0,53.5,45.6,NaN
524965,2022-08-08 13:26,690.6,137.9,546.6,650.0,641.9,30.7,71.0,3.4,4.1,0.5,222.5,16.3,994,0,0.0,54.0,45.7,NaN

In [30]:
##df_zscore_scipy = df['GHI', 'DNI', 'DHI', 'ModA', 'ModB', 'WS', 'WSgust'].select_dtypes(include=np.number).apply(zscore)
df_zscore_scipy = df[['GHI', 'DNI', 'DHI', 'ModA', 'ModB', 'WS', 'WSgust']].apply(zscore)
df_zscore_scipy = df_zscore_scipy>3
df_zscore_scipy.sum()

GHI         89
DNI          0
DHI       3738
ModA        27
ModB        63
WS        3109
WSgust    3500
dtype: int64

In [ ]:
plt.bar(df['Timestamp'],df['GHI'])
plt.show()

KeyboardInterrupt: